[package]
name = "expire_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-std = "1.11.0"
num = "0.4.0"
parking_lot = "0.12.1"
smallvec = "1.8.0"
time = { path = "../time" }
