[package]
name = "ip_txt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
z85 = "3.0.5"
addrbytes = { path = "../addrbytes" }
anyhow = "1.0.57"
