name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: docker
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        uses: docker/setup-buildx-action@v2
      -
        uses: docker/login-action@v2
        with:
          username: irmw
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          tags: rmwl/build:latest
