name: update

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '59 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    strategy:
      matrix:
        # platform: [windows-latest]
        # platform: [macos-latest]
        #python-version: [3.9]
        # platform: [macos-latest,windows-latest]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/cache@v3
        if: startsWith(matrix.platform, 'ubuntu')
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-cache

      - uses: docker/setup-buildx-action@v2
        if: startsWith(matrix.platform, 'ubuntu')

      - uses: docker/build-push-action@v2
        if: startsWith(matrix.platform, 'ubuntu')
        with:
          context: docker
          push: false
          tags: rmw-link-build:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: build-linux
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          ./docker/build.sh
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
